In [2]:
import tensorflow as tf

In [4]:
print (tf.__version__)

2.19.0


In [31]:
#Single number is scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scalar.ndim

0

In [25]:
# number with direction
vector = tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [9]:
vector.ndim

1

In [35]:
matrix = tf.constant([[10,10],[10,11]])
matrix.ndim

2

In [36]:
#2D array numbers
second_matrix = tf.constant([[10,10],[10,11],[10,12],[10,13],[10,14]])
second_matrix.ndim

2

In [34]:
third_matrix = tf.constant([[[10,10],[10,11]],[[10,13],[10,13]]])
print(third_matrix)
third_matrix.ndim

tf.Tensor(
[[[10 10]
  [10 11]]

 [[10 13]
  [10 13]]], shape=(2, 2, 2), dtype=int32)


3

In [24]:
second_matrix=tf.constant([[5.6,7.3], [3.45,8.25],[3.11,9.23],[4.34,2.34],[8.4,6.23]], dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[5.6  7.3 ]
 [3.45 8.25]
 [3.11 9.23]
 [4.34 2.34]
 [8.4  6.23]], shape=(5, 2), dtype=float32)


In [26]:
# Tensor : n-dimensional array of number

tensor=tf.constant ([[[1,2], [3,4]], [[5,6], [7,8]]])
tensor


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [30]:
#Find the shape,rank and size of tensor
print("Scalar Information")
print("Shape:",scalar.shape)
print ("Dimension:",scalar.ndim)
print("Rank:",tf.rank(scalar).numpy())
print("Size:",tf.size(scalar))


Scalar Information
Shape: ()
Dimension: 0
Rank: 0
Size: tf.Tensor(1, shape=(), dtype=int32)


In [32]:
print("Vector Information")
print("Shape:",vector.shape)
print ("Dimension:",vector.ndim)
print("Rank:",tf.rank(vector).numpy())
print("Size:",tf.size(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [37]:
print("Matrix Information")
print("Shape:",matrix.shape)
print ("Dimension:",matrix.ndim)
print("Rank:",tf.rank(matrix).numpy())
print("Size:",tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank: 2
Size: tf.Tensor(4, shape=(), dtype=int32)


In [38]:
print("Tensor Information")
print("Shape:",tensor.shape)
print ("Dimension:",tensor.ndim)
print("Rank:",tf.rank(tensor).numpy())
print("Size:",tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank: 3
Size: tf.Tensor(8, shape=(), dtype=int32)
