In [1]:
import tensorflow as tf
import numpy as np

**multiply by column [m x n]*[n x P] = [m x p]**

In [9]:
tensor_a = tf.constant([[1,2],[3,4],[6,7]],dtype=tf.int32)
tensor_b = tf.constant([[5,6],[7,8]],dtype=tf.int32)

print("Shape of A:",tensor_a.shape)
print("Shape of B:",tensor_b.shape)

Shape of A: (3, 2)
Shape of B: (2, 2)


In [10]:
tensor_c = tf.matmul(tensor_a, tensor_b)
print(tensor_c)
print("Shape of C:",tensor_c.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [79 92]], shape=(3, 2), dtype=int32)
Shape of C: (3, 2)


In [12]:
x = tf.constant([[1,0,-1],[2,3,1]],dtype=tf.float32)
y = tf.constant([[4,],[5,],[6,]],dtype=tf.float32)
print("Shape of x:",x.shape)
print("Shape of y:",y.shape)

Shape of x: (2, 3)
Shape of y: (3, 1)


In [13]:
z = tf.matmul(x, y)
print(z)
print("Shape of Z:",z.shape)

tf.Tensor(
[[-2.]
 [29.]], shape=(2, 1), dtype=float32)
Shape of Z: (2, 1)


**Transpose**

In [20]:
a = tf.constant([[[1,0,-1],[2,3,1]],[[3,4,5],[6,7,8]]],dtype=tf.int32)
print(a)
print("Shape of a:",a.shape)

tf.Tensor(
[[[ 1  0 -1]
  [ 2  3  1]]

 [[ 3  4  5]
  [ 6  7  8]]], shape=(2, 2, 3), dtype=int32)
Shape of a: (2, 2, 3)


In [21]:
b = tf.transpose(a)
print(b)
print("Shape of b:",b.shape)


tf.Tensor(
[[[ 1  3]
  [ 2  6]]

 [[ 0  4]
  [ 3  7]]

 [[-1  5]
  [ 1  8]]], shape=(3, 2, 2), dtype=int32)
Shape of b: (3, 2, 2)


In [23]:
#swap row to column in a block
c = tf.transpose(a,perm=[0,2,1])
print(c)
print("Shape of c:",c.shape)

tf.Tensor(
[[[ 1  2]
  [ 0  3]
  [-1  1]]

 [[ 3  6]
  [ 4  7]
  [ 5  8]]], shape=(2, 3, 2), dtype=int32)
Shape of c: (2, 3, 2)


Reshape
- tf.reshape(tensor,new_shape)

In [27]:
f = tf.reshape(a,shape=(2,3,-1)) #-1 will automatically assign the number
print(f)

tf.Tensor(
[[[ 1  0]
  [-1  2]
  [ 3  1]]

 [[ 3  4]
  [ 5  6]
  [ 7  8]]], shape=(2, 3, 2), dtype=int32)


In [25]:
e = tf.reshape(a,shape=(1,6,2))
print(e)

tf.Tensor(
[[[ 1  0]
  [-1  2]
  [ 3  1]
  [ 3  4]
  [ 5  6]
  [ 7  8]]], shape=(1, 6, 2), dtype=int32)


In [33]:
#TASK: Reshape (2,6) -> (3,4) and (1,12)
tensor_given = tf.constant ([[1, 2, 3, 4, 5, 6],  [7, 8, 9, 10, 11, 12]], dtype=tf.int32)
print(tensor_given)
reshape_A = tf.reshape(tensor_given,shape=(3,4))
print("\n",reshape_A)
reshape_b = tf.reshape(tensor_given,shape=(1,12))
print("\n",reshape_b)


tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)

 tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)

 tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
