In [1]:
import tensorflow as tf

In [2]:
#Creating Tensor using Varibale
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [7]:
changeable_tensor[0].assign(7)
changeable_tensor[1].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 9], dtype=int32)>

In [16]:
#random tensors
random_tensors = tf.random.Generator.from_seed(42)
random_tensors = random_tensors.normal(shape=(2,2))
random_tensors

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [12]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.06619239, 0.933179  , 0.7387562 , ..., 0.7762009 , 0.93196857,
        0.71625483],
       [0.34007537, 0.8653722 , 0.98061454, ..., 0.13174891, 0.41642356,
        0.7316917 ],
       [0.74543023, 0.8600582 , 0.3182478 , ..., 0.9276062 , 0.08547592,
        0.8303225 ],
       ...,
       [0.46468103, 0.9936154 , 0.49187958, ..., 0.24650466, 0.70905817,
        0.26591337],
       [0.91064954, 0.1304388 , 0.5633999 , ..., 0.9115914 , 0.07233608,
        0.8669878 ],
       [0.74330056, 0.48137677, 0.17919743, ..., 0.62157   , 0.65122545,
        0.7061056 ]], dtype=float32)>

In [13]:
random_tensor_3=tf.random.uniform(shape=(50,50),minval=1,maxval=2)
random_tensor_3

<tf.Tensor: shape=(50, 50), dtype=float32, numpy=
array([[1.1592106, 1.1831396, 1.8624421, ..., 1.9464188, 1.6113033,
        1.0713975],
       [1.576181 , 1.5478798, 1.7811081, ..., 1.7947544, 1.3422616,
        1.0821949],
       [1.2340524, 1.0583467, 1.1943165, ..., 1.6955041, 1.8161767,
        1.1635137],
       ...,
       [1.6886296, 1.5910834, 1.6611577, ..., 1.5302396, 1.0258403,
        1.9140198],
       [1.5487258, 1.1818498, 1.0304378, ..., 1.5451279, 1.4929905,
        1.5036507],
       [1.4390154, 1.3003634, 1.0609277, ..., 1.009652 , 1.1318798,
        1.1051824]], dtype=float32)>

In [17]:
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random. Generator.from_seed (42)
random_tensor_4 = random_tensor_4.normal (shape=(3,2))
random_tensor_3, random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [18]:
#different seed from tensor
random_tensor_3=tf.random.Generator.from_seed(42) #same sequence of “random” numbers.
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random. Generator.from_seed (15)
random_tensor_4 = random_tensor_4.normal (shape=(3,2))
random_tensor_3, random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [22]:
#create tensor using zeros

#int
tensor_zeros=tf.zeros(shape=(3,4), dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [21]:
#float
tensor_zeros1=tf.zeros(shape=(3,4), dtype=tf.dtypes.float32)
tensor_zeros1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [23]:
#tensor with all ones
tensor_one=tf.ones(shape=(3,4), dtype=tf.dtypes.float32)
tensor_one

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>