In [1]:
import tensorflow as tf
import numpy as np

In [6]:
numpy_array = np.arange(1,25,dtype=np.int16)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [8]:
tensor_numpy = tf.constant(numpy_array,shape=(2,3,4)) #2 block, 3 row, 4 columns
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [12]:
print("Tensor Information")
print("Shape:",tensor_numpy.shape)
print ("Dimension:",tensor_numpy.ndim)
print("Rank:",tf.rank(tensor_numpy).numpy())
print("Size:",tf.size(tensor_numpy ))
print("DataType of elements: ", tensor_numpy.dtype)
print("Element along axis 0: ", tensor_numpy.shape[0])
print("Element along axis 1: ", tensor_numpy.shape[1])
print("Element along axis 2: ", tensor_numpy.shape[2])
print("Toatal number of element: \t", tf.size (tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Element along axis 0:  2
Element along axis 1:  3
Element along axis 2:  4
Toatal number of element: 	 24


In [13]:
#working with item of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [17]:
#working with first two items of each dimension
tensor_numpy[:1,:3,:2] #1 block,3 rows, 2 columns

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]]], dtype=int16)>

In [20]:
#working with first items of each dimension
tensor_numpy[:2,:3,:1] #2 block,3 rows, 1 columns

<tf.Tensor: shape=(2, 3, 1), dtype=int16, numpy=
array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]], dtype=int16)>