In [10]:
import tensorflow as tf
import numpy as np

In [11]:
tensor_one = tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [12]:
#add
tensor_one + 15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [13]:
#sub
tensor_one - 3
tf.subtract(tensor_one,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -4,  -6],
       [-13, -10]], dtype=int32)>

In [14]:
#mult
tensor_one * 3
tf.multiply(tensor_one,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[165, 135],
       [ 30,  75]], dtype=int32)>

In [16]:
#div
tensor_one / 2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [18]:
#square
tf.square(tensor_one)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [26]:
#square root, #cast -> change datatype
tf.sqrt(tf.cast(tensor_one, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.3166249, 3.       ],
       [1.4142135, 2.236068 ]], dtype=float32)>

Exercise Create two tensors with random values between 0 and 1, shape is  
[6,300] **Find out the following details: **  
• Number of elements  
• Size,  
• Rank,  
• Shape  

In [37]:
random_tensor_one = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
random_tensor_two = tf.random.Generator.from_seed(42).normal(shape=(6,300))

print("First Tensor Details")
print("Number of element:",tf.size(random_tensor_one).numpy())
print("Size:",random_tensor_one.shape)
print("Rank:",random_tensor_one.ndim)
print("Shape:",random_tensor_one.shape)

print("\nSecond Tensor Details")
print("Number of element:",tf.size(random_tensor_two).numpy())
print("Size:",random_tensor_two.shape)
print("Rank:",random_tensor_two.ndim)
print("Shape:",random_tensor_two.shape)

First Tensor Details
Number of element: 1800
Size: (6, 300)
Rank: 2
Shape: (6, 300)

Second Tensor Details
Number of element: 1800
Size: (6, 300)
Rank: 2
Shape: (6, 300)
