### Mathematical Operation for 1D array

In [33]:
import numpy as np

In [34]:
our_arr = np.array([900,200,300,100,800,600,700,850])

In [35]:
print(our_arr)

[900 200 300 100 800 600 700 850]


In [36]:
# Sum
print (np.sum(our_arr))

4450


In [37]:
# Mean value
print(np.mean(our_arr))

556.25


In [38]:
# Minimum value
print(np.min(our_arr))

100


In [39]:
# Maximum value
print(np.max(our_arr))

900


In [40]:
# Index of min
print(np.argmin(our_arr))

3


In [41]:
# Index of max
print(np.argmax(our_arr))

0


##### Sort

In [42]:
sorted_arr = np.sort(our_arr)
print(sorted_arr)

[100 200 300 600 700 800 850 900]


In [43]:
# Is there any item over 500
print(np.any(sorted_arr>500))

True


In [44]:
# Is all item over 500
print(np.all(sorted_arr>500))

False


In [45]:
# Is all item over 99
print(np.any(sorted_arr>99))

True


In [46]:
# Where value > 500
print(np.where(sorted_arr>500))

(array([3, 4, 5, 6, 7]),)


In [56]:
# Print all index where number is greater than 500
for num in np.where(sorted_arr>500):
    print(num)

[3 4 5 6 7]


In [62]:
# Print all number that is greater than 500 in sorted array
for num in (sorted_arr[sorted_arr>500]):
    print(num)

600
700
800
850
900


In [75]:
# Print all number that is greater than 500 in original array 
for num in our_arr[our_arr>500]:
    print(num)

900
800
600
700
850


##### Slice

In [89]:
#slice array[start:last]
print(our_arr[0:2])

[900 200]


In [72]:
#slice array[start:empty] <- start index to last index
print(our_arr[2:])

[300 100 800 600 700 850]


In [92]:
#slice array[empty:last] <- show all item before particular index
print(sorted_arr[:2])

[100 200]


##### Step

In [91]:
#Step = how much to move between each number.[start:end:Step]
print(sorted_arr)

[100 200 300 600 700 800 850 900]


In [88]:
our_slice = sorted_arr[1:6:2] # take every 2nd element from index 1 to 6
print(our_slice)

[200 600 800]


In [86]:
every_third_element = sorted_arr[: :3] # Every 3rd number
print(every_third_element)

[100 600 850]


Slice Reverse

In [102]:
#slice reverse
print(f"Original Array {sorted_arr}")
print(f"New Array {sorted_arr[: :-1]}")

Original Array [100 200 300 600 700 800 850 900]
New Array [900 850 800 700 600 300 200 100]


In [103]:
# Last 5 element
print(sorted_arr[-5:])

[600 700 800 850 900]


In [122]:
#sort reverse
print(f"Original Array {our_arr}")
print(f"Original arrray in reverse {our_arr[::-1]}") 
print(f"Sort Ascending {np.sort(our_arr)}") #sort ascending
print(f"Sort Descending {np.sort(our_arr)[::-1]}")  #sort descending

Original Array [900 200 300 100 800 600 700 850]
Original arrray in reverse [850 700 600 800 100 300 200 900]
Sort Ascending [100 200 300 600 700 800 850 900]
Sort Descending [900 850 800 700 600 300 200 100]
