In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("students.xlsx")
df

Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

In [4]:
marks = df['Marks'].to_numpy()
print("Numpy array of marks")
print(marks)

Numpy array of marks
[85 90 78 92 34]


In [6]:
print("Highest mark: ", np.max(marks))

Highest mark:  92


In [7]:
print("Lowest mark: ", np.min(marks))

Lowest mark:  34


In [8]:
print("Average mark: ", np.mean(marks))

Average mark:  75.8


#### Location
      .loc : label based
      .iloc : index based

In [26]:
print ('Original Dataframe')
print(df)
print ('\nLocation: Label Based')
print (df.loc[2,['Name','Marks']])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

Location: Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [22]:
print ('Original Dataframe')
print(df)
print ('\nLocation: Label Based')
print (df.loc[2,'Name'])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

Location: Label Based
Bob


In [35]:
print ('Original Dataframe')
print(df)
print ('\nLocation: Label Based')
print (df.loc[2,['Name']])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

Location: Label Based
Name    Bob
Name: 2, dtype: object


In [15]:
print ('Original Dataframe')
print(df)
print ('\nLocation: Index Based')
print (df.iloc[4])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

Location: Index Based
Name     maya
Age        34
Marks      34
Name: 4, dtype: object


In [37]:
print ('Original Dataframe')
print(df)
print ('\nLocation: Index Based')
print (df.iloc[4, [1,2]])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

Location: Index Based
Age      34
Marks    34
Name: 4, dtype: object


#### Axis is Numpy:
      1. Axis 0 - Vertical Direction , Column-Wise
      2. Axis 1 - Horizontal Direction, Row-Wise

#### Example 1
    We have 2 students mark in 3 subject
    [[45,50,59],[30,45,49]] 

In [40]:
mark_Array = np.array([[45,50,59],[30,45,49]])
print(mark_Array)

[[45 50 59]
 [30 45 49]]


In [46]:
#Sum of all value
print(np.sum(mark_Array))

278


In [45]:
#sum down of each column
print(np.sum(mark_Array,axis=0))

[ 75  95 108]


In [44]:
#sum down of each row
print(np.sum(mark_Array,axis=1))

[154 124]


#### Example 2 

In [47]:
df

Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4   maya   34     34

 Find student who got highest mark

In [65]:
topper = df.loc[df['Marks'].idxmax(),'Name']
print(topper)

Sara


 Find student who got less mark

In [66]:
loser = df.loc[df['Marks'].idxmin(),'Name']
print(loser)

maya


In [69]:
top_index = df['Marks'].idxmax()
print(top_index)
top_student = df.iloc[top_index, df.columns.get_loc("Name")]
print(top_student)

3
Sara
