## numpy introduction and usage
numpy for fast numerical calculation

In [67]:
import numpy as np

### 1D array

In [68]:
array1 = np.array([10,20,30,40,50])
print(array1)

[10 20 30 40 50]


### 2D array

In [69]:
array2 = np.array([[10,20,30,40,50],[60,70,90,80,500]])
print(array2)

[[ 10  20  30  40  50]
 [ 60  70  90  80 500]]


### 3D array

In [70]:
array3 = np.array([[[10,20,30,40,50],[60,70,90,80,500]],[[10,20,30,40,50],[60,70,90,80,500]]])
print(array3)

[[[ 10  20  30  40  50]
  [ 60  70  90  80 500]]

 [[ 10  20  30  40  50]
  [ 60  70  90  80 500]]]


### Find out dimension

In [71]:
array1.ndim

1

In [72]:
array2.ndim

2

In [73]:
array3.ndim

3

### Write an array of 5 student marks

In [74]:
marks = np.array([80,70,75,99,89])
print("Array of marks")
print(marks)

Array of marks
[80 70 75 99 89]


### Write an array to take marks of 5 students in 3 subject
###### - math, english, chemistry

In [75]:
mark_subject = np.array([[50,45,49],[40,42,45],[35,76,98],[23,45,89],[80,75,77]])
print("2D Array of marks")
print(mark_subject)

2D Array of marks
[[50 45 49]
 [40 42 45]
 [35 76 98]
 [23 45 89]
 [80 75 77]]


### Write an array to take marks of 4 students in 3 subject for 2 semester
###### Subject: math, english, chemistry
###### Names:   'mia','mit','mira','zay'
###### Semester: Sem1,Sem2
###### 4x3x2

In [76]:
mark_sub = np.array([ #[(mat sem1, mat sem2),(eng sem1, eng sem2) ,(chem sem1, chem sem2)]
                     [[91,98],[60,70],[78,89]], #mia
                     [[12,34],[56,78],[90,89]], #mit
                     [[21,32],[43,54],[65,76]], #mira
                     [[87,98],[40,75],[70,34]]  #zay
                    ])
print(mark_sub)

[[[91 98]
  [60 70]
  [78 89]]

 [[12 34]
  [56 78]
  [90 89]]

 [[21 32]
  [43 54]
  [65 76]]

 [[87 98]
  [40 75]
  [70 34]]]


### Write an array to take weather of 2 cities in 3 days for 3x in a day

###### Time slot: morning,noon,evening
###### Cities name: KL,Delhi
###### Saturday, Sunday, Monday


In [77]:
weather = np.array([[[#KL('morning','noon','evening')
                     20,25,29], #saturday
                     [25,30,19], #sunday
                     [30,25,22]], #monday
                    
                      #Delhi('morning','noon','evening')
                     [[19,25,18], #saturday
                     [25,31,24], #sunday
                     [22,26,23] #monday
                    ]])
print(weather)

[[[20 25 29]
  [25 30 19]
  [30 25 22]]

 [[19 25 18]
  [25 31 24]
  [22 26 23]]]


In [78]:
weather1 = np.array([[[20,25,29], [25,30,19],[30,25,22]], [[19,25,18],[25,31,24],[22,26,23]]])
print(weather1)

[[[20 25 29]
  [25 30 19]
  [30 25 22]]

 [[19 25 18]
  [25 31 24]
  [22 26 23]]]


### Data Type

In [79]:
print(array1.dtype)
print(array2.dtype)
print(weather.dtype)

int64
int64
int64


### Basic Information
    shape = row & column
    size = number of element
    dtype = data type
    ndim = dimension

In [86]:
student = np.array(['ali bin kabir','mira','maua','izat','noriz'])
print(student)

['ali bin kabir' 'mira' 'maua' 'izat' 'noriz']


In [83]:
student.shape

(4,)

In [88]:
student.size

5

In [85]:
student.dtype

dtype('<U5')

In [87]:
student.ndim

1

### Mathematical Operation

In [89]:
print(array1)

[10 20 30 40 50]


In [93]:
# Sum
print (np.sum(array1)

150


In [94]:
# Mean value
print(np.mean(array1))

30.0


In [95]:
# Minimum value
print(np.min(array1))

10


In [102]:
# Maximum value
print(np.max(array1))

50


In [100]:
# Index of min
print(np.argmin(array1))

0


In [101]:
# Index of max
print(np.argmax(array1))

4


In [113]:
our_arr = np.array([900,200,300,100,800,600,700,850])

In [123]:
# Sort
sorted_arr = np.sort(our_arr)
print(sorted_arr)

[100 200 300 600 700 800 850 900]


In [124]:
# Is there any item over 500
print(np.any(sorted_arr>500))

True


In [125]:
# Is all item over 500
print(np.all(sorted_arr>500))

False


In [129]:
# Is all item over 99
print(np.all(sorted_arr>99))

True


In [128]:
# Where value > 500
print(np.where(sorted_arr>500))

(array([3, 4, 5, 6, 7]),)


In [131]:
# Print all index where number is greater than 500
for num in np.where(sorted_arr>500):
    print(num)

[3 4 5 6 7]
